### ISSUE TITLE
Test failures with "wrong state" on aarch64

### ISSUE THREAD

**Issue by jfrederickson** [wingo/fibers#101] opened 2023-12-30 22:43 UTC
I noticed some strange test failures in the [guile-goblins](https://gitlab.com/spritely/guile-goblins) tests, and @cwebber suggested that I try running the Fibers tests on my machine too as guile-goblins depends on Fibers. And sure enough, I had some tests fail in the Fibers test suite too. Output of `make check` below.

This is on commit f8ec3c48e511d12e0166959befd254632d21ae90 on an MNT Reform with the a311d CPU module.

```
jfred@reform:~/src/fibers [env]$ make check
make  check-am
make[1]: Entering directory '/home/jfred/src/fibers'
make  check-TESTS
make[2]: Entering directory '/home/jfred/src/fibers'
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/jfred/src/fibers/./tests/basic.scm
WARNING: (tests basic): imported module (fibers) overrides core binding `sleep'
;;; compiled /home/jfred/.cache/guile/ccache/3.0-LE-8-4.6/home/jfred/src/fibers/tests/basic.scm.go
scheduler objects can be printed with a reasonable length:
assert (<= (string-length (pk (call-with-output-string (lambda (port) (display (make-scheduler #:parallelism 4) port))))) (+ (string-length "#<scheduler  (remote-peers: (   ))>") (* 4 2 (sizeof (quote *))))) equal to #t: 
;;; ("#<scheduler 395e240 (remote-peers: (395e1e0 395e180 395e120))>")
ok
Testing dynamic-wind* ...
ok!
Testing dynamic-wind* ...
ok!
Testing dynamic-wind* ...
ok!
Testing dynamic-wind* in a loop with concurrency and preemption ...

;;; (#:for out-guard #:expected (#t #t #t #t #t #f) #:got (#t #t #t #t #t #t))
Uncaught exception in task:
In fibers.scm:
    172:8  5 (_)
In tests/basic.scm:
   195:10  4 (_)
    112:4  3 (run-dynamic-wind-loop 30000 #<procedure poke-reschedul?>)
In fibers/scheduler.scm:
   293:10  2 (dynamic-wind* _ _ _)
In tests/basic.scm:
    111:8  1 (_)
In ice-9/boot-9.scm:
  1685:16  0 (raise-exception _ #:continuable? _)
ice-9/boot-9.scm:1685:16: In procedure raise-exception:
wrong state

;;; (#:for out-guard #:expected (#t #t #t #t #t #f) #:got (#t #t #t #t #t #t))
Uncaught exception in task:
In fibers.scm:
    172:8  5 (_)
In tests/basic.scm:
   195:10  4 (_)
    112:4  3 (run-dynamic-wind-loop 30000 #<procedure poke-reschedul?>)
In fibers/scheduler.scm:
   293:10  2 (dynamic-wind* _ _ _)
In tests/basic.scm:
    111:8  1 (_)
In ice-9/boot-9.scm:
  1685:16  0 (raise-exception _ #:continuable? _)
ice-9/boot-9.scm:1685:16: In procedure raise-exception:
wrong state

;;; (#:for out-guard #:expected (#t #t #t #t #t #f) #:got (#t #t #t #t #t #t))
Uncaught exception in task:
In fibers.scm:
    172:8  5 (_)
In tests/basic.scm:
   195:10  4 (_)
    112:4  3 (run-dynamic-wind-loop 30000 #<procedure poke-reschedul?>)
In fibers/scheduler.scm:
   293:10  2 (dynamic-wind* _ _ _)
In tests/basic.scm:
    111:8  1 (_)
In ice-9/boot-9.scm:
  1685:16  0 (raise-exception _ #:continuable? _)
ice-9/boot-9.scm:1685:16: In procedure raise-exception:
wrong state

;;; (#:for in-guard #:expected (#t #f #f #f #f #f) #:got (#t #t #t #f #f #f))
Uncaught exception in task:
In fibers.scm:
    172:8  5 (_)
In tests/basic.scm:
   195:10  4 (_)
    112:4  3 (run-dynamic-wind-loop 30000 #<procedure poke-reschedul?>)
In fibers/scheduler.scm:
   289:10  2 (dynamic-wind* #<procedure 31adc80 at tests/basic.scm:?> ?)
In tests/basic.scm:
    111:8  1 (_)
In ice-9/boot-9.scm:
  1685:16  0 (raise-exception _ #:continuable? _)
ice-9/boot-9.scm:1685:16: In procedure raise-exception:
wrong state

;;; (#:for in-guard #:expected (#f #f #f #f #f #f) #:got (#t #t #t #f #f #f))
Uncaught exception in task:
In fibers.scm:
    172:8  8 (_)
In tests/basic.scm:
   195:10  7 (_)
    112:4  6 (run-dynamic-wind-loop 30000 #<procedure poke-reschedul?>)
In fibers/scheduler.scm:
    286:2  5 (dynamic-wind* _ #<procedure 31adc30 at tests/basic.sc?> ?)
In tests/basic.scm:
    128:7  4 (_)
In fibers/scheduler.scm:
   403:10  3 (suspend-current-task _)
In unknown file:
Exception thrown while printing backtrace:
In procedure frame-local-ref: Argument 2 out of range: 0
ice-9/boot-9.scm:1685:16: In procedure raise-exception:
wrong state
```

**Comment by wingo** [comment] 2024-04-23 06:48
This is almost surely the same as #83.  Closing as duplicate; please do re-open if the issue is closed in error.

**Closed by wingo** 2024-04-23 06:48 UTC
